# TIPOS "INT" E "FLOAT"
# INT -> NUMEROS INTEIROS
# O TIPO INT REPRESENTA QUALQUER NUMERO
# POSITIVO OU NEGATIVO. INT SEM SINAL E CONSIDERADO
# POSITIVO.

print('inteiro', 11) #int
print('inteiro',-11) #int
print('inteiro',0) #int

#FLOAT -> NUMERO COM PONTO FLUTUANTE 
#O TIPO REPRESENTA QUALQUER NUMERO
#POSITIVO OU NEGATIVO COM PONTO FLUTUANTE
#FLOAT SEM SENAL É CONSIDERADO POSITIVO
print('float', 1.1)
print('float', 10.11)


#A FUNÇÃO "TYPE" MOSTRA O TIPO QUE O PYTHON 
#INFERIU AO VALOR+

print(type(2.6))
print(type(2))
print(type('vagner'))

