# TIPO DE DADO 'BOOL' (BOOLEAN)
# AO QUESTIONAR ALGO EM UM PROGRAMA,
# SÓ EXISTE ALGO EM UM PROGRAMA,
# SIM (TRUE) OU NÃO (FALSE).
# EXISTEM VARIOS OPERADORES PARA QUESTIONAR
# DENTRE ELES O ==, QUE É UM OPERADOR LOGICO QUE
# QUESTIONA SE UM VALOR É IGUAL A OUTRO

print(10 == 10)# SIM => TRUE (VERDADEIRO)
print(10 == 11)# NÃO => FALSE (FALSO) 
print(type(10 == 11))# FALSE
print(type(10 == 10))# TRUE

